- name: make sure fish is installed
  package:
    name: fish
    state: present

- name: symlink dotfiles
  file:
    src: "{{ ansible_env.PWD }}/roles/fish/files/{{ item }}"
    path: ~/.config/fish/{{ item }}
    state: link
    follow: false
    force: yes
  loop:
    - config.fish
    - fish_variables
    - functions
