#!/usr/bin/env sh
help() {
    echo "Usage: ./install"
    echo "-h (print this message)"
}

while getopts ':p:w:d:g:h' opt; do
    case $opt in
        h)
            help
            exit
            ;;
        ?)
            echo "Invalid Parameter given. $(help)"
            ;;
    esac
done

os="$(uname)"

if [ "$os" = "Darwin" ]; then
    if ! [ -x "$(command -v brew)" ]; then
        echo "Installing homebrew"
        curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh
    fi

    if ! [ -x "$(command -v ansible-playbook)" ]; then
        echo "Install ansible"
        brew install ansible
    fi

    echo "Running mac ansible playbook"
    ansible-playbook --ask-become-pass \
                     -i hosts \
                     mac.yml

elif [ "$os" = "Linux" ]; then
    if ! [ -x "$(command -v ansible-playbook)" ]; then
        echo "Install ansible"
        sudo pacman -S ansible
    fi

    if ! [ -f "/etc/sudoers.d/20-aur-ansible" ]; then
        echo "Set up aur_ansible user and sudoers"
        sudo useradd -m aur_ansible
        sudo cp sudoers/20-aur-ansible /etc/sudoers.d/20-aur-ansible
        sudo chown root:root /etc/sudoers.d/20-aur-ansible
        sudo chmod 440 /etc/sudoers.d/20-aur-ansible
    fi

    echo "Install galaxy roles"
    ansible-galaxy install -r galaxy_requirements.yml

    echo "Running linux ansible playbook"
    ansible-playbook --ask-become-pass \
                     -i hosts \
                     linux.yml
else
   echo "Unknown OS: $os"
   exit 1
fi
