- name: Setup local environment
  hosts: localhost
  roles:
    - locale
    - git
    - arch
    - gnupg
    - dunst
    # - dwm
    - bspwm
    # - dmenu
    # - zsh
    - fish
    - st
    - ctags
    - nvim
    - emacs
    - dav
    - ranger
    - taskwarrior
    - mail
    - code
