- name: install dwm dependencies
  become: yes
  package:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xsetroot
      - freetype2
      - libx11
      - libxft
      - libxinerama
      - xclip
      - feh
    state: present

- name: clone dwm
  git:
    repo: https://github.com/snowiow/dwm
    dest: ~/workspace/dwm
    version: snow
    accept_hostkey: yes

- name: make and make install dwm
  make:
    chdir: "/home/{{ ansible_user_id }}/workspace/dwm"
    target: install
  become: yes

- name: clone dwmstatus
  git:
    repo: https://github.com/snowiow/dwmstatus
    dest: ~/workspace/dwmstatus
    version: snow
    accept_hostkey: yes

- name: make and make install dwmstatus
  make:
    chdir: "/home/{{ ansible_user_id }}/workspace/dwmstatus"
    target: install
  become: yes

- name: symlink xinitrc
  file:
    src: "{{ansible_env.PWD}}/roles/dwm/files/xinitrc"
    path: ~/.xinitrc
    state: link
    force: yes

- name: create local bin
  file:
    path: ~/.local/bin
    state: directory

- name: symlink touchpad_toggle
  file:
    src: "{{ansible_env.PWD}}/roles/dwm/files/touchpad_toggle.sh"
    path: ~/.local/bin/touchpad_toggle.sh
    state: link
    force: yes
