# Ruby
- name: install fish-rbenv
  shell:
    cmd: fisher add rbenv/fish-rbenv
    executable: fish

# Java
- name: enable jenv in fish shell
  copy:
    src: "{{ ansible_env.PWD }}/roles/programming/files/{{ item }}"
    dest: "~/.config/fish/functions/{{ item }}"
  with_items:
    - jenv.fish
    - export.fish

# Rust
- name: ensure fish completion directory
  file:
    path: ~/.config/fish/completions
    state: directory
    recurse: yes

- name: install rustup completions for fish shell
  shell: ~/.cargo/bin/rustup completions fish > ~/.config/fish/completions/rustup.fish
  args:
    creates: ~/.config/fish/completions/rustup.fish

- name: install rust nightly
  shell: rustup toolchain add nightly

- name: install racer
  shell: cargo +nightly install racer

- name: install rust src
  shell: rustup component add rust-src
