# Ruby
- name: install rbenv
  package:
    name: rbenv
    state: present

# Java
- name: install jenv
  package:
    name: jenv
    state: present

# Clojure
- name: install leiningen
  package:
    name: leiningen
    state: present

# Javascript
- name: install fnm
  homebrew:
    name: Schniz/tap/fnm
    state: present

# Rust
- name: install rust via rustup
  shell: curl https://sh.rustup.rs -sSf | sh -s -- -y

# Godot engine
- name: install godot engine
  homebrew_cask:
    name: godot
    state: present

# LLVM Compiler
- name: install llvm toolchain
  homebrew:
    name: llvm
    state: present
