- name: install gnupg for verified packages from spacelpa
  become: yes
  package:
    name: gnupg

- name: install cmake
  become: yes
  package:
    name: cmake

- name: install libvterm
  become: yes
  package:
    name: libvterm

- name: install emacs AUR packages
  aur:
    name:
      - emacs27-git
