- name: install gnupg for verified packages from spacelpa
  package:
    name: gnupg

- name: install cmake
  package:
    name: cmake

- name: install libvterm
  package:
    name: libvterm

- name: install emacs AUR packages
  aur:
    become: yes
    become_user: aur_builder
    name:
      - emacs27-git
