- name: install mail software
  become: yes
  package:
    name: msmtp,
          neomutt,
          offlineimap,
          stack,
          notmuch
    state: present

- name: create neomutt config directory
  file:
    path: ~/.config/mutt/
    state: directory

- name: create encrypted password file for mail_privat
  shell: echo "{{ lookup('env', 'MAIL_PRIVATE_PW') }}" | gpg --recipient snow --encrypt > ~/.mailpw_privat.gpg
  when: lookup('env', 'MAIL_PRIVATE_PW') != ""

- name: create encrypted password file for mail_arbeit
  shell: echo "{{ lookup('env', 'MAIL_WORK_PW') }}" | gpg --recipient snow --encrypt > ~/.mailpw_arbeit.gpg
  when: lookup('env', 'MAIL_WORK_PW') != ""
