- name: make sure packages are installed
  package:
    name:
      - awscli
      - bash
      - gmp
      - htop
      - jq
      - leiningen
      - rbenv
      - ripgrep
      - tree
      - watch
      - wget
