- name: install starship AUR packages
  roles:
    - kewlfft.aur
  tasks:
    - aur:
        become: yes
        become_user: aur_builder
        name:
          - nerd-fonts-jetbrains-mono
          - starship
