- name: create nvim config directory
  file:
    path: ~/.config/nvim
    state: directory

- name: symlink config files
  file:
    src: "{{ ansible_env.PWD }}/roles/nvim/files/{{ item }}"
    path: "~/.config/nvim/{{ item }}"
    state: link
    follow: false
    force: yes
  loop:
    - ftplugin
    - plugin
    - init.vim
    - pack
    - UltiSnips
